### ISSUE TITLE
Работа с локальным KML

### ISSUE THREAD

**Issue by alexgubanow** [shramov/leaflet-plugins#164] opened 2015-05-07 11:29 UTC
Я разрешил работу с локальными файлами и кросс доменные запросы, и OpenLayers карта работает с локальным KML, а ваш плагин не расчитан на роботу с локальными файлами?
Это не проблема браузера, так как OpenLayers работают с этим же локальным KML.

I let to work with local files and cross domain requests, and OpenLayers maps works with a local KML, and your plug-in is not designed for the robot to local files?
This is no problem browser, as OpenLayers work with the same local KML.

**Comment by alexgubanow** [comment] 2015-05-12 18:09
решение найдено, if (req.status === 200 || req.status === 0) cb(req.responseXML, options);
дело в том что при работе с локальным файлом статус будет = 0, а скрипт ждет статус = 200, добавляем условие или статус =0 и все работает

**Comment by brunob** [comment] 2015-07-14 09:06
Hi @alexgubanow sorry but i can only read french, english or spanish :\

**Comment by alexgubanow** [comment] 2015-07-14 09:10
Hi @brunob I translated for you.

**Comment by brunob** [comment] 2015-07-14 09:11
With the help of an automatic translate, it seems you have a bug with kml tested locally. Form my side, kml example works well locally accessed on file: type url with Firefox. But it doesn't work with Chromium or Opera.

**Comment by brunob** [comment] 2015-07-14 09:13
This one seems to be a duplicate of #44, i think we can close it.

**Comment by alexgubanow** [comment] 2015-07-14 09:14
you can not work with local files due to built-in protection. that would be earned, it is necessary to launch the browser to disable protection mode to do this opera --disable-web-security.

**Comment by alexgubanow** [comment] 2015-07-14 09:16
I have to work with the leaflet, use my application.

**Comment by brunob** [comment] 2015-12-02 12:57
@alexgubanow any news about this, do you have a patch to propose in a pull request or can we close this issue ?

**Comment by alexgubanow** [comment] 2015-12-03 15:08
I completely rewrote your code and using it in my p roject . In a couple of days, I will send the code .  
 2 декабря 2015, 14:57:39, от "b_b" < notifications@github.com >: 
 
@alexgubanow  any news about this, do you have a patch to propose in a pull request or can we close this issue ?

**Comment by brunob** [comment] 2019-07-24 14:22
3 years later, we have not seen the code, i think we can close this one :p

**Closed by brunob** 2019-07-24 14:22 UTC
Labels: question
