### ISSUE TITLE
how can i disable the start and end Marker Icon in leaflet Gpx

### ISSUE THREAD

**Issue by labneu** [shramov/leaflet-plugins#268] opened 2018-02-17 13:04 UTC
Help!
how can i disable the start and end Marker Icon in leaflet Gpx:
By default gpx.js will use pin-icon-start.png, pin-icon-end.png and pin-shadow.png as the marker icons URLs for, respectively, the start marker, the end marker and their drop shadow. Since it might not be convenient that these images have to reside under the same directory as your HTML page, it is possible to override the marker icon URLs and sizes by passing a marker_options object to the GPX options object.

**Comment by brunob** [comment] 2018-02-17 14:38
duplicate of #266

**Closed by brunob** 2018-02-17 14:38 UTC
