### ISSUE TITLE
Проблема с маркерами на яндекс карте. 

### ISSUE THREAD

**Issue by er24scorpion** [shramov/leaflet-plugins#172] opened 2015-06-23 11:44 UTC
Когда зумлю, все иконки будто расползаются/сползаются. На osm и google такого нет.

**Comment by brunob** [comment] 2015-06-23 11:47
hi @er24scorpion sorry but i can only read french, english or spanish :\

**Comment by er24scorpion** [comment] 2015-06-23 11:57
Sorry. 
When I do something zoom, then my markers spread out in different directions. And polylines too.

**Comment by brunob** [comment] 2015-06-23 12:22
Hard to help without a link to your page or a jsfiddle...

**Comment by er24scorpion** [comment] 2015-06-23 13:04
http://jsfiddle.net/0bd5g1gc/1/ 
Bug when I zoom and drag map on Yandex tile.

**Comment by brunob** [comment] 2015-06-23 13:09
Ok i see, this bug is a duplicate of #111 since yandex tiles are implemented like google tiles...

As i said in this comment https://github.com/shramov/leaflet-plugins/issues/97#issuecomment-114226868 : 

> This script may need a refactoring but i don't plan to do it, feel free to provide pull requests for it :)

**Closed by brunob** 2015-06-23 13:09 UTC
Labels: question

**Comment by johnd0e** [comment] 2019-05-24 09:16
Duplicate of #129
