### ISSUE TITLE
Google plugin: inconsistent zooming behavior between base map and overlays

### ISSUE THREAD

**Issue by bpeng** [shramov/leaflet-plugins#244] opened 2016-08-30 05:18 UTC
As shown [here](https://hazmap-143a7.firebaseapp.com/quakes-map-google.html), when the map is zooming in or out, overlay points are moving relative to the base layer, which are consistent with OSM or [Bing](https://hazmap-143a7.firebaseapp.com/quakes-map-bing1.html).

**Comment by brunob** [comment] 2016-08-30 08:05
Closing since it's a duplicate of #111 and many others...

**Closed by brunob** 2016-08-30 08:05 UTC
Labels: duplicate
